### ISSUE TITLE
[Bug]: Entity card tap action

### ISSUE THREAD

**Issue by gabi1324** [piitaya/lovelace-mushroom#1192] opened 2023-07-06 07:16 UTC
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

With the new release of HA (2023.7), the "Assist" tap action has been added. 
When I select "Assist" as a tap action, the card gives an error.
![SmartSelect_20230706_101404_Home Assistant](https://github.com/piitaya/lovelace-mushroom/assets/61083655/5a22b7ea-98ab-46e4-918e-b21a06b75e5c)

### Expected Behavior

The cards need to be updated to support this new feature.

### Context

YAML state
```yaml

```

### Environment

```markdown
- HA Version: 2023.7
- Mushroom: 2.8.1
```

**Comment by piitaya** [comment] 2023-07-06 07:43
Duplicate of https://github.com/piitaya/lovelace-mushroom/issues/1191

**Closed by piitaya** 2023-07-06 07:43 UTC
Labels: bug
