### ISSUE TITLE
[Feature]: Simple switch card and Button card

### ISSUE THREAD

**Issue by ihaettypo** [piitaya/lovelace-mushroom#751] opened 2022-09-29 05:37 UTC
### Is your feature request related to a problem?

If you use entity card with tap-action as a switch card, sometimes it's difficult to distinguish between the card which shows more-info upon clicking with which calls a service upon clicking.

I'd like to call them action card (a card that runs a service or change the status of a deivce upon clicking) and information card (a card that displays information only, and shows more-info upon clicking).

### Describe the solution you'd like

Maybe the way to solve this is to give some visual cues.

For example for switch entities, add a switch control in the card. (Equivalent to the brightness control of mushroom light card)

For button enttities, add a button in the card.

**Comment by spali** [comment] 2022-10-06 20:36
I started to use only the hold action for more info exactly because of this. So it's at least the same for all.
Means short click executes something if it's supported (switch) and long click always opens the more info dialog.
It's not ideal in my mind.
Because all my buttons have an icon and a name or status as primary text, I would love to allow to define actions for the icon (switch) and for the primary text something different (open more info).
This way I don't have to fiddle around with long clicks, which I don't like 😉 
Maybe this feature this would help @ihaettypo too.

**Comment by piitaya** [comment] 2022-10-24 16:13
Duplicate of #446

**Closed by piitaya** 2022-10-24 16:13 UTC
Labels: enhancement
