### ISSUE TITLE
[Feature]: Customizable badges

### ISSUE THREAD

**Issue by alexanderlindstrom** [piitaya/lovelace-mushroom#522] opened 2022-05-24 13:31 UTC
### Is your feature request related to a problem?

-

### Describe the solution you'd like

I would like to suggest a feature that will make it possible for users to customize badges, as far as I've seen the only badge possible is the question mark when an entity is not available. See Image.

Perhaps a question mark should the default for not available, but a usecase could be to show some data in the badge when it's on/off. Eg. Temperature, battery level etc. 

![SmartSelect_20220524-152555_Home Assistant](https://user-images.githubusercontent.com/1754686/170047221-2cb96cde-378a-4f68-b1fd-481e7434e254.jpg)

**Comment by piitaya** [comment] 2022-05-24 14:12
Duplicate of https://github.com/piitaya/lovelace-mushroom/issues/84

**Closed as not planned** 2022-05-24 14:12 UTC
Labels: duplicate, enhancement

**Comment by alexanderlindstrom** [comment] 2022-05-24 14:15
Pardon. Should have searched for similar issues. Thanks

**Comment by piitaya** [comment] 2022-05-24 14:25
No problem 🙂 
I linked your issue to the other.
