### ISSUE TITLE
Android App: it's not possible to turn off the vibration feedback from mushroom cards

### ISSUE THREAD

**Issue by Raingren** [piitaya/lovelace-mushroom#364] opened 2022-04-19 18:33 UTC
Hello,

if you use the android app from HA you get an vibration feedback if you press mushroom cards(Light Card, Entity Card). I've tried turning the vibration feedback off but without sucsess. The standard switching elements do not give any vibration feedback . Only mushroom elements give vibration feedback even if the vibration feedback is disabled in the profile settings.

Is this a bug that only happens to me?

Regards Raingren

 - Device: Huawei P30 Pro
 - OS: Android 10

**Comment by piitaya** [comment] 2022-04-19 18:47
Duplicate of #93

**Closed by piitaya** 2022-04-19 18:47 UTC
Labels: bug
