### ISSUE TITLE
[Bug]: Media player not showing volume buttons

### ISSUE THREAD

**Issue by cypherbits** [piitaya/lovelace-mushroom#1078] opened 2023-03-17 19:51 UTC
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

I have a media_player entity produced with a Samsung TV integration that works everything fine with the media card.

I have a media_player entity produced with a DLNA integration for an old Samsung TV. This has a problem:
- mute volume button: OK.
- slider volume: OK.
- volume buttons: KO. No way of showing them.

The entity has the volume_level attribute.

This is very weird.

### Expected Behavior

Expected the volume buttons to be shown like the other integration.

### Steps To Reproduce

Maybe using a DNLA media_player?

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: Firefox or Android app
- HA Version: 2023.3.4    Frontend 20230309.0
- Mushroom: v2.6.1
```

### Anything else?

Working media player attributes:

```
source_list: TV, HDMI, +tdp, AS TV, AccuWeather - Weather for Life, Atresplayer, Clan Rtve, Clan en Rtve.es, DAZN, Disney Channel, Disney+, EL PAÍS VÍDEO, Eurosport Player, Facebook Watch, Filmin, Google Play Películas y TV, HBO España, InvestoPro, Kids Safe Video Player para YouTube videos, LaLigaSportstv, Logitravel, Microcanales, Mitele, Movistar Plus+, MyOperaPlayer, Netflix, Opciones de privacidad, Orange TV, Pluto TV, Prime Video, RT, RTVE Play, Rakuten TV, Samsung Club, Sky, Sleep Baby Owl - Ruido blanco para bebés, Spotify - Música y podcasts, TED, TV Cast, The Dream VR, The KARAOKE Channel TV App, Vevo, Vimeo, Web Browser, YouTube, YouTube Kids, beIN CONNECT, e-Manual
device_class: tv
friendly_name: Samsung 5 Series (32)
supported_features: 20413
volume_level: 0.07
is_volume_muted: false
```

Not working old tv:

```
sound_mode_list: FactoryDefaults
volume_level: 0.09
is_volume_muted: false
media_content_id: 
media_duration: 0
media_track: 0
shuffle: false
repeat: off
friendly_name: TV-32C5100
supported_features: 197132
```

**Comment by cypherbits** [comment] 2023-03-17 19:56
Just saw the `device_class: tv` difference. Maybe is this?

**Comment by piitaya** [comment] 2023-03-31 07:39
Hello. The volume buttons are only show when the entity supports `SUPPORT_VOLUME_STEP` (which your entity TV-32C5100 doesn't support). Does the `volume_up` `volume_down` service works using the developer tools ? If yes, how much has the volume been increased?

**Comment by piitaya** [comment] 2023-04-08 11:14
Duplicate of https://github.com/piitaya/lovelace-mushroom/issues/782.

**Closed by piitaya** 2023-04-08 11:14 UTC
Labels: bug
