### ISSUE TITLE
[Bug]: Cards fails to render on the home assistant app on an old iPad OS 12.5.7

### ISSUE THREAD

**Issue by zachary-duquette** [piitaya/lovelace-mushroom#1278] opened 2023-11-02 03:56 UTC
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

Mushroom cards fails to render on the home assistant app on an old iPad OS 12.5.7 with version 3.2.0. Looking through the log files, I see no mushroom errors.

Reverting to 3.1.0 fixes the issue.

Screenshot of 3.2.0 on a new dashboard with a single mushroom-entity-card.
![3.2.0](https://github.com/piitaya/lovelace-mushroom/assets/10729043/b7ac5f85-bb12-4734-b7c1-34aad32c989c)

Screenshot of 3.1.0 on the same dashboard.
![3.1.0](https://github.com/piitaya/lovelace-mushroom/assets/10729043/69495a61-2b3d-42a1-9e25-be1198d655d9)

### Steps To Reproduce

1. Have an old neglected iPad.
2. Open any dashboard with Mushroom cards.
3. See nothing.

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: iPad OS 12.5.7 Home Assistant App
- HA Version: 2023.11
- Mushroom: 3.2.0
```

**Comment by peterson1190** [comment] 2023-11-02 07:21
Same for me. The issue is, that all the custom card devs slowly starts adopting the new Webkit, which is not supporting older devices, WallPanel dev managed to add backwards compatibility, so I think it is solvable, but I'm no expert by any means.

**Comment by zachary-duquette** [comment] 2023-11-02 15:38
Update to 3.2.2 works, thank you!

**Comment by piitaya** [comment] 2023-11-02 15:39
Thank ! I close this issue 🙂

**Closed by piitaya** 2023-11-02 15:39 UTC
Labels: bug
