### ISSUE TITLE
[Feature]: Using icons (material design, or other HA accessible icons) in template cards

### ISSUE THREAD

**Issue by wishie** [piitaya/lovelace-mushroom#447] opened 2022-05-07 07:56 UTC
### Is your feature request related to a problem?

I would love to be able to use mdi icons inside template cards. Right now, I have to use emojis, and they differ from device to device.

### Describe the solution you'd like

To be able to use mdi icons in template cards.

### Describe alternatives you've considered

I currently use emojis.

### Additional context

![Screen Shot 2022-05-07 at 5 55 36 pm](https://user-images.githubusercontent.com/635844/167244841-d97c5345-79a1-4adb-bba2-10a9e189d6b6.png)

**Comment by KTibow** [comment] 2022-07-01 19:28
Duplicate of #327?

**Closed** 2022-09-16 09:15 UTC
Labels: enhancement
