### ISSUE TITLE
Bug: UI border of cards on dashboards

### ISSUE THREAD

**Issue by ryanevans-dev** [piitaya/lovelace-mushroom#839] opened 2022-11-09 16:58 UTC
### Current Behavior

There is now an border around cards on the new HA UI, for example on the chip card there is an border which group them all, this was previously not the case.

### Expected Behavior

For the border to be invisible or not present at all.

I suspect this is HA updates themselves causing this border rather than this integration, but can it be overridden?

### Steps To Reproduce

Go onto HA dashboard
Add chip card (plus others)
You will see a faint border across the screen.

### Environment

```markdown
- Browser: Mobile App
- HA Version: 2022.11.2
- Mushroom: 2.1.3
```

**Comment by piitaya** [comment] 2022-11-09 17:05
Duplicate of https://github.com/piitaya/lovelace-mushroom/issues/822 https://github.com/piitaya/lovelace-mushroom/issues/813 https://github.com/piitaya/lovelace-mushroom/issues/795 and already fixed. You need to update to the latest mushroom version.

**Closed by piitaya** 2022-11-09 17:05 UTC
Labels: bug

**Comment by chench00** [comment] 2022-11-25 16:52
@piitaya  I am running v2.4.1 and still see the borders:

![Screen Shot 2022-11-25 at 11 52 18 AM](https://user-images.githubusercontent.com/63960113/204028783-7ddead73-fe37-4213-85ae-eda31c8f4281.png)

Do I need to add any extra code?

**Comment by piitaya** [comment] 2022-11-25 16:55
Do you have this in your console ?
![CleanShot 2022-11-25 at 17 55 11](https://user-images.githubusercontent.com/5878303/204029171-c9493289-41f0-4503-bc13-54e3ebec525f.png)

**Comment by chench00** [comment] 2022-11-25 16:58
I see this in HACS:

![Screen Shot 2022-11-25 at 11 57 33 AM](https://user-images.githubusercontent.com/63960113/204029556-499d985f-f480-4dd4-8448-466ef8af4d5e.png)

**Comment by piitaya** [comment] 2022-11-25 16:58
Look into your browser console. I think you have a cache issue 🙂

**Comment by chench00** [comment] 2022-11-25 17:01
![Screen Shot 2022-11-25 at 12 00 49 PM](https://user-images.githubusercontent.com/63960113/204029960-de61b069-80ae-430e-b776-bc6dc828cb67.png)

**Comment by piitaya** [comment] 2022-11-25 17:04
Oh wait, it's in a `stack-in-card` card ? Stack in card is not fixed with the new border for cards : https://github.com/custom-cards/stack-in-card/pull/47

**Comment by piitaya** [comment] 2022-11-25 17:09
Add this to your yaml
```yaml
  styles:
    '--chip-border-width': 0
    '--chip-background': none
```

**Comment by chench00** [comment] 2022-11-25 17:47
I only uploaded the .js fine and the border disappeared. I didn't have to change anything.

        views:
          - title: Home
        type: custom:stack-in-card
        mode: vertical
        cards:
          - type: custom:stack-in-card
            mode: horizontal
            cards:
              - type: custom:mushroom-chips-card
                chips:
                  - type: template
                    entity: sensor.time_date
                    icon: mdi:date
                    icon_color: yellow
                    content: '{{ as_timestamp(now()) | timestamp_custom("%m-%d-%y", True) }}'
                    tap_action:
                      action: more-info
                    hold_action:
                      action: none
                    double_tap_action:
                      action: none
                    card_mod: null
                    alignment: center
                    style: |
                      ha-card {
                          box-shadow: 0px 0px;
                      }
              - type: custom:mushroom-chips-card
                chips:
                  - type: template
                    entity: sensor.time_date
                    icon: mdi:date
                    icon_color: yellow
                    content: '{{ as_timestamp(now()) | timestamp_custom("%I:%M%p", True) }}'
                    tap_action:
                      action: more-info
                    hold_action:
                      action: none
                    double_tap_action:
                      action: none
                    card_mod: null
                    alignment: center
                    style: |
                      ha-card {
                          box-shadow: 0px 0px;
                      }
                alignment: center
              - type: custom:mushroom-chips-card
                chips:
                  - type: template
                    entity: sensor.hallway_thermostat_temperature
                    content: 'Inside, {{ states(entity)}} °F '
                    icon_color: |-
                      {% set state=states('sensor.hallway_thermostat_hvac_state') %}
                      {% if state=='off' %}
                      gray
                      {% elif state=='heating' %}
                      red
                      {% endif %}
                    icon: mdi:thermometer
                    tap_action:
                      action: more-info
                      browser_mod:
                        command: popup
                        title: Thermostat
                        card:
                          type: thermostat
                          entity: climate.hallway
                    hold_action:
                      action: none
                    double_tap_action:
                      action: none
                    alignment: end
                    card_mod: null
                    style: |
                      ha-card {
                        box-shadow: 0px 0px;
                      }
                alignment: end
            card_mod: null
            style: |
              ha-card {
                      box-shadow: 0px 0px;
                  }
          - type: custom:mushroom-title-card
            title: >-
              {% if now().hour  < 5 %} Good Night{% elif now().hour < 12 %} Good
              Morning{% elif now().hour < 18 %} Good Afternoon{% else %} Good Evening{%
              endif %}, Costa Family
            subtitle: Welcome to Home Assistant
          - type: custom:stack-in-card
            mode: horizontal
            cards:
              - type: custom:mushroom-template-card
                icon: mdi:lock
                layout: vertical
                tap_action:
                  action: more-info
                hold_action:
                  action: none
                double_tap_action:
                  action: none
                entity: alarm_control_panel.house
                icon_color: |-
                  {% set state=states('alarm_control_panel.house') %}
                  {% if state=='disarmed' %}
                  green
                  {% elif state=='armed_home' %}
                  red
                  {% elif state=='armed_away' %}
                  red          
                  {% elif state=='arming' %}
                  red
                  {% elif state=='triggered' %}
                  red
                  {% elif state=='pending' %}
                  yellow
                  {% endif %}
                secondary: |-
                  {% set state=states('alarm_control_panel.house') %}
                  {% if state=='disarmed' %}
                  Disarmed
                  {% elif state=='armed_home' %}
                  Armed Home
                  {% elif state=='armed_away' %}
                  Armed Away
                  {% elif state=='pending' %}
                  Pending           
                  {% endif %}
                multiline_secondary: true
                primary: Alarm
              - type: custom:mushroom-template-card
                icon: mdi:home-automation
                layout: vertical
                tap_action:
                  action: call-service
                  service: automation.reload
                hold_action:
                  action: none
                double_tap_action:
                  action: none
                icon_color: green
                multiline_secondary: true
                primary: Automation
                secondary: Reload
              - type: custom:mushroom-template-card
                icon: mdi:car
                layout: vertical
                tap_action:
                  action: more-info
                hold_action:
                  action: none
                double_tap_action:
                  action: none
                entity: sensor.abcorp
                icon_color: |-
                  {% set state = states('sensor.abcorp')|float(-1) %}
                  {% if state >= 50 %} red
                  {% elif state >= 45 %} yellow
                  {% else %} green
                  {% endif %}
                secondary: '{{ states(''sensor.abcorp'')}}'
                multiline_secondary: true
                primary: ABCorp
              - type: custom:mushroom-template-card
                icon: mdi:home
                layout: vertical
                tap_action:
                  action: more-info
                hold_action:
                  action: none
                double_tap_action:
                  action: none
                entity: input_select.harmony_activity
                icon_color: |-
                  {% set state=states('input_select.harmony_activity') %}
                  {% if state=='PowerOff' %}
                  green
                  {% elif state=='Watch TV' %}
                  red
                  {% elif state=='Plex TV' %}
                  red         
                  {% elif state=='Play Switch' %}
                  red           
                  {% endif %}
                secondary: '{{ states(''input_select.harmony_activity'')}}'
                multiline_secondary: true
                primary: Hub

**Comment by chench00** [comment] 2022-11-27 16:22
@piitaya Any other suggestions?

**Comment by piitaya** [comment] 2022-11-27 17:46
I don't use stack in card so I can not help with that 😔
