### ISSUE TITLE
Entity picture

### ISSUE THREAD

**Issue by chertvl** [piitaya/lovelace-mushroom#146] opened 2022-02-20 08:18 UTC
**Is your feature request related to a problem? Please describe.**
Is it possible to make a feature that allows you use entity pictures in cards?
For example, I have several template sensors with .png pictures instead of icons.
Better if we could set image path in card setting, as it realized in custom -button-card.

Thanks!

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by piitaya** [comment] 2022-02-20 17:07
It's a duplicate of #100. We don't plan to support `png` or `svg` image for now because it's not standard for HA entity. It's only supported by person card because the person entity is the entity only with image support.

**Comment by chertvl** [comment] 2022-02-20 19:20
I would like to argue. Set png as entity icon its HA default feature (customize docs).
And we can see this custom icon evertwhere - logbook, more-info, etc,  but not in the Mushroom cards.
![image](https://user-images.githubusercontent.com/38353584/154860268-ca94723a-708a-4097-8815-fc2fb1548e56.png)

**Comment by piitaya** [comment] 2022-02-20 19:58
Thank for the explanation 😊. I didn't known it was possible to do that. 
I think we need to refactor the components before because adding new options will duplicate a lot of code.

**Comment by brandensilva** [comment] 2022-02-21 20:39
Neat, I didn't know that was possible either. I'd love to do a custom set of icons for entities.

**Closed** 2022-04-24 16:14 UTC
Labels: enhancement
