### ISSUE TITLE
[Bug]: error in google console

### ISSUE THREAD

**Issue by riddik14** [piitaya/lovelace-mushroom#1537] opened 2024-09-12 18:02 UTC
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

It seems to work fine but I get this error:

```
Uncaught NotSupportedError: Failed to execute 'define' on 'CustomElementRegistry': the name "mushroom-select" has already been used with this registry
    at mushroom.js:29:61
    at mushroom.js:29:76
    at n (mushroom.js:1:963)
    at mushroom.js:571:62'''
```

### Expected Behavior

//

### Steps To Reproduce

chrome consolle 

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: chrome
- HA Version: 2024.09.release
- Mushroom: release
```

### Anything else?

//

**Comment by piitaya** [comment] 2024-11-13 14:45
Duplicate of https://github.com/piitaya/lovelace-mushroom/issues/1562

**Closed as not planned by piitaya** 2024-11-13 14:45 UTC
Labels: bug
