### ISSUE TITLE
Feature Request: A Popup Card

### ISSUE THREAD

**Issue by j-loewen** [piitaya/lovelace-mushroom#119] opened 2022-02-14 20:52 UTC
Hello,

First, I would like to thank you for your magnificent work.

It would be cool if you would create a button/entity type card that opens a pop up with a card in it. A card in where you can define one card that is shown if you click on this button/entity.

**Comment by pierrecle** [comment] 2022-02-14 21:29
Duplicate of #56 , the reason of close with won't fix is given here: https://github.com/piitaya/lovelace-mushroom/issues/56#issuecomment-1031925191

I also close your issue, it won't come until a quiet long time. It rises too much questions and the easiest answer for this would be "take mushroom out of lovelace, create a standalone dashboard app like appdaemon with a dedicated configurator that uses HASS API and we're free to handle popup in an easy way for user", which is absolutely not what we want. It conflicts with our user-friendy non-negotiable prerequisite, even if it would be way easier for us on some points.

**Closed by pierrecle** 2022-02-14 21:29 UTC
Labels: enhancement
