### ISSUE TITLE
[Bug]: Swipe Card Click

### ISSUE THREAD

**Issue by wernerhp** [piitaya/lovelace-mushroom#1302] opened 2023-11-28 20:18 UTC
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

When I use Android swipe navigation to navigate back from a subview and I swipe over a Mushroom Card the click action fires on the Mushroom card (entity, template etc) b fore the back navigation.

### Expected Behavior

When I swipe on a Mushroom card the click event should not trigger.  The click event should only trigger for clicks.

### Steps To Reproduce

With an Android device with gesture navigation enabled 
Add mushroom cards that span the entire width of the screen (or multiple in a grid) to a subview
Navigate to the subview
Swipe from the edge of the screen towards the left to navigate back to the main dashboard.

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: HA companion App Android
- HA Version: At least the last 6 versions
- Mushroom: Latest and at least 6 months ago
```

**Comment by piitaya** [comment] 2024-02-07 16:47
I close the issue as it's not a Mushroom issue because it can be reproduced with other built-in cards.

**Closed by piitaya** 2024-02-07 16:47 UTC
Labels: bug
