### ISSUE TITLE
[Bug]: Template card update issue

### ISSUE THREAD

**Issue by theetron** [piitaya/lovelace-mushroom#568] opened 2022-06-24 09:11 UTC
### Current Behavior

I have multiple template cards calling the remote send command. These cards are in a grid card. In design mode, switching between these different template cards, the following items are not updated but stay all the same:

- Commands
- Repeats
- Delay Seconds
- Hold Seconds

### Expected Behavior

I want to see all my configured values for the remote send command for all my template cards when I select them in design mode.

### Steps To Reproduce

1. add a grid card with a few columns
2. put in a few template cards and select for all the remote.send_command service
3. specify some settings for each card and you will notice the above 4 mentioned attributes are not changed when switching between these cards.

### Environment

```markdown
- Home Assistant Core 2022.6.7
- Home Assistant Supervisor 2022.05.3
- Home Assistant OS 8.2
- Browser: Chrome
- Device: rPi4
- Mushroom v2.0.0
```

**Comment by KTibow** [comment] 2022-07-01 00:34
Are you using a translator or are not native to English? I can't really understand you. Could you add a video recording or screenshots?

**Comment by piitaya** [comment] 2022-07-01 08:14
Can you provide your entire yaml ?

**Comment by theetron** [comment] 2022-07-01 10:13
This is the yaml of the card:

`
type: vertical-stack
cards:
  - type: custom:mushroom-title-card
    title: ''
    subtitle: Apparaten
  - type: markdown
    content: '**ledstrip**'
  - square: false
    columns: 5
    type: grid
    cards:
      - type: custom:mushroom-template-card
        primary: ''
        secondary: ''
        icon: mdi:lightbulb-off
        icon_color: black
        tap_action:
          action: call-service
          service: remote.send_command
          data:
            device: ledstrip
            command:
              - light off
          target:
            device_id: cfbd342087c08c86344667e0391dfb76
        layout: vertical
        double_tap_action:
          action: none
        hold_action:
          action: none
      - type: custom:mushroom-template-card
        primary: ''
        secondary: ''
        icon: mdi:lightbulb
        icon_color: red
        tap_action:
          action: call-service
          service: remote.send_command
          data:
            device: ledstrip
            command:
              - light on
              - red
          target:
            device_id: cfbd342087c08c86344667e0391dfb76
        layout: vertical
        hold_action:
          action: none
        double_tap_action:
          action: none
      - type: custom:mushroom-template-card
        primary: ''
        secondary: ''
        icon: mdi:lightbulb
        icon_color: blue
        tap_action:
          action: call-service
          service: remote.send_command
          data:
            device: ledstrip
            command:
              - light on
              - blue
          target:
            device_id: cfbd342087c08c86344667e0391dfb76
        layout: vertical
        double_tap_action:
          action: none
        hold_action:
          action: none
      - type: custom:mushroom-template-card
        primary: ''
        secondary: ''
        icon: mdi:lightbulb
        icon_color: green
        tap_action:
          action: call-service
          service: remote.send_command
          data:
            device: ledstrip
            command:
              - light on
              - green
          target:
            device_id: cfbd342087c08c86344667e0391dfb76
        layout: vertical
        double_tap_action:
          action: none
        hold_action:
          action: none
      - type: custom:mushroom-template-card
        primary: ''
        secondary: ''
        icon: mdi:lightbulb
        icon_color: white
        tap_action:
          action: call-service
          service: remote.send_command
          data:
            device: ledstrip
            command:
              - light on
              - white
          target:
            device_id: cfbd342087c08c86344667e0391dfb76
        layout: vertical
        double_tap_action:
          action: none
        hold_action:
          action: none
      - type: custom:mushroom-template-card
        primary: ''
        secondary: flash
        icon: mdi:numeric-1-box
        icon_color: ''
        tap_action:
          action: call-service
          service: remote.send_command
          data:
            device: ledstrip
            command:
              - light on
              - flash
          target:
            device_id: cfbd342087c08c86344667e0391dfb76
        layout: vertical
        double_tap_action:
          action: none
        hold_action:
          action: none
      - type: custom:mushroom-template-card
        primary: ''
        secondary: strobe
        icon: mdi:numeric-2-box
        icon_color: ''
        tap_action:
          action: call-service
          service: remote.send_command
          data:
            device: ledstrip
            command:
              - light on
              - strobe
          target:
            device_id: cfbd342087c08c86344667e0391dfb76
        layout: vertical
        double_tap_action:
          action: none
        hold_action:
          action: none
      - type: custom:mushroom-template-card
        primary: ''
        secondary: fade
        icon: mdi:numeric-3-box
        icon_color: ''
        tap_action:
          action: call-service
          service: remote.send_command
          data:
            device: ledstrip
            command:
              - light on
              - fade
          target:
            device_id: cfbd342087c08c86344667e0391dfb76
        layout: vertical
        double_tap_action:
          action: none
        hold_action:
          action: none
      - type: custom:mushroom-template-card
        primary: ''
        secondary: flash
        icon: mdi:numeric-4-box
        icon_color: ''
        tap_action:
          action: call-service
          service: remote.send_command
          data:
            device: ledstrip
            command:
              - light on
              - smooth
          target:
            device_id: cfbd342087c08c86344667e0391dfb76
        layout: vertical
        double_tap_action:
          action: none
        hold_action:
          action: none
        badge_icon: ''
        badge_color: ''
  - square: false
    columns: 2
    type: grid
    cards:
      - type: custom:mushroom-light-card
        entity: light.projector_hessel
        icon: mdi:lightbulb-night
        use_light_color: false
        show_color_temp_control: false
        show_color_control: true
        show_brightness_control: true
        name: Projector
      - type: custom:mushroom-template-card
        primary: Playstation 5
        secondary: '{{states(''switch.wcd_04'')}}'
        icon: mdi:power-plug-outline
        icon_color: |-
          {% if is_state('switch.wcd_04','on') %}
          blue
          {% endif %}
        entity: switch.wcd_04
        tap_action:
          action: more-info
`

**Comment by KTibow** [comment] 2022-07-01 18:36
When I said to send screenshots/video, I meant of the problem, not how you configured it.

**Comment by piitaya** [comment] 2022-07-01 18:41
I reproduced the problem. I don't known if it a problem with the grid card or the mushroom card. I will test with official cards 🙂

**Comment by theetron** [comment] 2022-07-02 07:59
> When I said to send screenshots/video, I meant of the problem, not how you configured it.

Donno how to react to this comment as I did show the issue in the movie..

**Comment by piitaya** [comment] 2024-08-21 10:05
Seems to be fixed with latest Home Assistant version as Mushroom is now using action editor from Home Assistant front-end.

**Closed by piitaya** 2024-08-21 10:05 UTC
Labels: bug
