### ISSUE TITLE
Add Popups

### ISSUE THREAD

**Issue by tkgsc** [piitaya/lovelace-mushroom#212] opened 2022-03-28 19:13 UTC
Is there any plans to eventually add popup for cards like lights, Climate and media players. or is that not possible without having to edit yaml?

**Comment by piitaya** [comment] 2022-04-01 10:24
Duplicate of #56. We are aware of this request but we want to focus on card for now (climate card, media card et...)

**Closed by piitaya** 2022-04-01 10:24 UTC
Labels: enhancement
