### ISSUE TITLE
Actions on icon click

### ISSUE THREAD

**Issue by usernein** [piitaya/lovelace-mushroom#685] opened 2022-08-11 11:12 UTC
### Is your feature request related to a problem?

I currently use tap_action to toggle my lights and hold_action to open the more-info menu, which is a bit slow imo. Trying to find a faster way of opening more-info, i tried double tapping but it made single tapping slower.
:

### Describe the solution you'd like

I'd like to be able to define an action to happen when i click specifically on the round icon. The tap_action should happen when i click on the rest of the card, normally
If "icon_tap_action" is not defined, the tap_action would work as it is right now

**Comment by Valdorama** [comment] 2022-10-11 03:10
This looks like a duplicate of [446](https://github.com/piitaya/lovelace-mushroom/issues/446).

Would be really nice to have this implemented.

**Comment by usernein** [comment] 2022-10-11 14:21
Yep, the requests are similar

But this is exactly the idea of this FR: https://github.com/piitaya/lovelace-mushroom/issues/446#issuecomment-1120379000

**Closed** 2022-10-24 16:13 UTC
Labels: enhancement
