### ISSUE TITLE
How to add icon to secondary information field

### ISSUE THREAD

**Issue by hesspoint** [piitaya/lovelace-mushroom#475] opened 2022-05-11 20:50 UTC
### Current Behavior

This is not really a bug but rather a question and I did not find a better place where to post it:

I use a template card on my dashboard.

I use the following code to display the number of open windows on that card as secondary information:

{%set state=states('sensor.office_open_windows')%}{% if state | int >= 1 %} W: {{ state }}{% else %}{% endif %}
So if e.g. one window is open it displays “W: 1”. So far so good. However it would look cooler if instead of the W I could display a mdi:window-open icon in front of the counter.

I tried adding mdi:window-open in various ways but I could not get it to work. Btw. I am happy with a static icon, does not have to be dynamic.

### Environment

```markdown
- OS:
- Node:
- Version:
- Hassio:
```

**Comment by piitaya** [comment] 2022-05-11 21:12
Hi 🙂 It's not possible to add icon because field are text only but you can use emoji of course.

**Comment by hesspoint** [comment] 2022-05-18 20:21
@piitaya great tip! I tried with Emojis and it looks pretty cool actually. Thanks

**Comment by hesspoint** [comment] 2022-05-19 19:45
![Screen Shot 2022-05-19 at 21 43 47](https://user-images.githubusercontent.com/67288231/169389646-40f997cf-ba8e-443e-acba-b9854cbaaf88.png)

I used the window one and the plant. so if at least one window/door in that room is open and/or at least one plant low on water it will show the icon with the number of affected entities.

**Comment by Atlas553** [comment] 2022-05-20 20:45
> ![Screen Shot 2022-05-19 at 21 43 47](https://user-images.githubusercontent.com/67288231/169389646-40f997cf-ba8e-443e-acba-b9854cbaaf88.png)
> 
> I used the window one and the plant. so if at least one window/door in that room is open and/or at least one plant low on water it will show the icon with the number of affected entities.

Really great Idea 👍🏼 I like it a lot. 

How do you insert a new line behind the temperature?

**Comment by Atlas553** [comment] 2022-05-20 20:49
> ![Screen Shot 2022-05-19 at 21 43 47](https://user-images.githubusercontent.com/67288231/169389646-40f997cf-ba8e-443e-acba-b9854cbaaf88.png)
> 
> I used the window one and the plant. so if at least one window/door in that room is open and/or at least one plant low on water it will show the icon with the number of affected entities.

Very nice idea 👍🏼 I like it a lot. 

How do you insert a new line behind the temperature?

**Comment by hesspoint** [comment] 2022-05-21 11:55
I simply did a linebreak in the secondar information field. Every new line in the code is also a new line in the UI. So if you have e.g an if else statement you need to write it all in one line. If you break it into multiple lines as I normally would it will create a bunch of blank lines.

**Comment by Atlas553** [comment] 2022-05-21 13:40
Oh man. I missed this one „Mehrzeilig sekundär?“ … 🤦🏼‍♂️ 

When I turn it on it works. 🤷🏼‍♂️

**Comment by KTibow** [comment] 2022-07-01 19:28
Duplicate of #327?

**Comment by piitaya** [comment] 2022-07-01 21:49
It's not planned to add mdi icons for now as there is emoji for that.

**Comment by KTibow** [comment] 2022-07-01 23:30
Can we close this issue as 1. not planned 2. a duplicate?

**Closed** 2022-09-16 09:14 UTC
Labels: question
