### ISSUE TITLE
Vertical Slider support

### ISSUE THREAD

**Issue by jsb5151** [piitaya/lovelace-mushroom#213] opened 2022-03-28 19:30 UTC
Not sure if this is easily feasible, but a vertical slider (kinda like the HomeKit slider) would be great!  I've been looking for something like this for a long while, and this design would fit the bill.

**Comment by piitaya** [comment] 2022-04-01 10:24
Duplicate of #56. We are aware of this request but we want to focus on card for now (climate card, media card et...)

**Closed by piitaya** 2022-04-01 10:24 UTC
Labels: enhancement
