### ISSUE TITLE
Ability to hide title

### ISSUE THREAD

**Issue by zuzuman** [piitaya/lovelace-mushroom#96] opened 2022-02-11 10:39 UTC
**Is your feature request related to a problem? Please describe.**
Sometime cards are too big, and some of them can be more compact

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/3532812/153577351-3516066f-20df-463f-b272-5622534f3cb6.png)
Add ability of compact view. No title. Main action (if needed) near sub actions.
Here you have cover and light

**Comment by piitaya** [comment] 2022-02-11 11:14
Looks like a duplicate of #34 but without the title. We need to find a solution that fits most of problem. The idea is not to propose 100 options to customize so we need to find the best 🙂

Today mushroom cards are : 
- state info
- state icon
- controls

We should look how we can define multiple layout and compose them for all cards but it's not the priority for now.

**Comment by brandensilva** [comment] 2022-02-11 18:03
I'd say from a UX perspective controls without titles are meaningless at describing the intended purpose of the card.

It's possible there is a title above hence the suggestion of this enhancement but each entity should be able to rely on its contents to describe what it impacts so users don't end up in a confused state of controls without intended targets.

**Comment by bemble** [comment] 2022-02-15 20:06
I can understand the last proposition and in fact, I like it. It makes sense when you have a view dedicated to a room with only one light, its name is not useful.

**Closed** 2022-06-25 19:34 UTC
Labels: enhancement
