### ISSUE TITLE
Entity card is not using the icon from the device class

### ISSUE THREAD

**Issue by envy** [piitaya/lovelace-mushroom#145] opened 2022-02-19 21:13 UTC
**Describe the bug**
I have window sensors that are binary sensors with a device class of `window`.
In the default HA card and in the entity list, they have a window icon that changes with the state of the sensor.
The mushroom entity card is instead showing a checkmark as the icon

**To Reproduce**
1. Add a binary sensor with device class `window`
2. Add a entity card for that sensor and look at the icon

**Expected behavior**
The entity card should use the icon of the entity.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/241552/154819159-95a05718-d98c-481d-868d-6171dfb663cb.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Browser Firefox
 - Version 97.0.1

**Comment by piitaya** [comment] 2022-02-20 17:11
Duplicate of #125. This is because we use icon rules from `https://github.com/custom-cards/custom-card-helpers`. I think we should write the rules in mushroom because the custom-cards repository doesn't seem to be very active.

**Closed** 2022-02-24 11:21 UTC
Labels: bug
