### ISSUE TITLE
[Bug]: Custom element doesn't exist mushroom-template-card on 4.1.0

### ISSUE THREAD

**Issue by jaymunro** [piitaya/lovelace-mushroom#1584] opened 2024-11-11 19:10 UTC
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

On old iPad the error has reared its head again. "custom element doesn't exist mushroom-template-card"

### Steps To Reproduce

Upgrade to Mushroom 4.1.0
Load dashboard on old iPad with iOS 12.5.7
Mushroom elements error out with the message "custom element doesn't exist mushroom-template-card" displayed instead of the card.
Downgrading Mushroom to 4.0.8 fixes the error.

### Context

YAML state
```yaml

```

### Environment

```markdown
- iOS: 12.5.7
- HA Version: 2023.12.1 (2023.508)
- Mushroom: 4.1.0
```

**Comment by Joshbloam** [comment] 2024-11-11 23:50
Same issue here. 
IPad air gen 1 IOS 12.5.7
HA Core 2024.11.1
Mushroom 4.1.0

**Comment by Cal-Can** [comment] 2024-11-12 02:06
Old Android Tablet
HA Core 2024.11.1
Mushroom 4.1.0

Happens in both web and HA app

Rolled back to 4.0.8

Logger: frontend.js.legacy.202411062
Source: components/system_log/__init__.py:331

Uncaught error from Chrome WebView 61.0.3163.98 on Android 8.1.0 SyntaxError: Unexpected token = %20Unexpected%20token%20=::
Uncaught error from Chrome WebView 61.0.3163.98 on Android 8.1.0 SyntaxError: Unexpected token ? %20Unexpected%20token%20::
Uncaught error from Chrome WebView 61.0.3163.98 on Android 8.1.0 SyntaxError: Unexpected token . %20Unexpected%20token%20.::
Uncaught error from Chrome 72.0.3626.76 on Android 8.1.0 SyntaxError: Unexpected token . Unexpected token .::
Uncaught error from Chrome 72.0.3626.76 on Android 8.1.0 SyntaxError: Unexpected token ? Unexpected token ::

**Comment by PKort** [comment] 2024-11-12 11:22
Same issue here: Lenovo Tab M10 (TB-X505F), running Android 10 (latest firmware installed: TB-X505f_S001149_221115_ROW). Checked in Home Assistant mobile app as and also WallPanel app.
Mushroom v4.0.8 is working correctly, while on v4.1.0 I get:
custom element doesn't exist mushroom-template-card
custom element doesn't exist mushroom-climate-card
and similarilly for other types of mushroom card.

**Comment by retracdev** [comment] 2024-11-12 23:19
There is some more info on #1582 I think.

**Comment by piitaya** [comment] 2024-11-13 08:05
Duplicate of #1582 
Thank you for the logs

**Closed by piitaya** 2024-11-13 08:05 UTC
Labels: bug
