### ISSUE TITLE
Hide Name, Icon on Light Card

### ISSUE THREAD

**Issue by eximo84** [piitaya/lovelace-mushroom#182] opened 2022-03-02 21:59 UTC
**Is your feature request related to a problem? Please describe.**

Would like to just utilise the beautiful slider, temp, colour control.  

**Describe the solution you'd like**

Being able to hide the name and icon on the light card would be great, can already hide state.

**Describe alternatives you've considered**

Tried to use card-mod to hide the .container but card-mod cannot seem to get to the div to hide it.

**Additional context**

**Comment by piitaya** [comment] 2022-03-02 22:20
Duplicate of #142.

**Comment by eximo84** [comment] 2022-03-03 00:14
Thanks for that link, did some tweaking with card-mod and got the card just displaying slider and control buttons.

```
type: custom:mushroom-light-card
entity: light.office_light
show_color_temp_control: true
show_brightness_control: true
layout: horizontal
show_color_control: true
name: ''
icon: ''
hide_state: true
use_light_color: true
card_mod:
  style: |
    .container.horizontal > ::slotted(:first-child) {
      display: none !important;
    }
```

**Comment by SaSa1983** [comment] 2022-03-09 12:16
If you set the name to a single space string, the name won't be shown
name: ' '

**Comment by FerretMonger** [comment] 2022-03-27 12:17
Even if I leave name and icon at '' (none) it still reserves space for them, which means that the slider becomes really short and hard to use.

**Closed** 2022-06-25 19:08 UTC
Labels: enhancement
