### ISSUE TITLE
[Bug]: The text has not been fully visible since the 3.4.0 update, while using card_mod

### ISSUE THREAD

**Issue by Je-sse** [piitaya/lovelace-mushroom#1356] opened 2024-02-01 18:58 UTC
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

The text in the Mushroom Template Card, when used in conjunction with card_mod, is not visible across the entire card area.
![image](https://github.com/piitaya/lovelace-mushroom/assets/61166497/96c2e393-0a62-4627-bbd4-c8ed199f9ef7)

### Expected Behavior

Before the upgrade (and after downgrade to 3.3.0) the text is fully visible again.
![image](https://github.com/piitaya/lovelace-mushroom/assets/61166497/145b796c-36c8-42ac-bcfd-c6a863e7b722)

### Steps To Reproduce

Create a Mushroom Template Card with this config:
```
type: custom:mushroom-template-card
primary: '{{ now().strftime(''%H:%M'') }}'
icon: mdi:timelapse
secondary: '{{ now().strftime(''%d %B'') }}'
card_mod:
  style: |
    ha-card {
       --card-primary-font-size: 60px;
       --card-secondary-font-size: 30px;
    }
    :host {
       --mush-icon-symbol-size: 1.75em;
       --mush-icon-size: 2.75em;
    }
```

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: Firefox, Android app
- HA Version: 2024.1.6
- Mushroom: 3.4.0
- Card-Mod: 3.4.2
```

**Comment by sdholden28** [comment] 2024-02-01 19:30
I can confirm this behavior. In 3.4.0, card size does not seem to increase with font size, like it did previously. This causes larger text to get clipped.

**Comment by Mr-HaleYa** [comment] 2024-02-01 23:57
It looks like the line height is messed up. I worked around it by adding explicit line height to each card but this is not ideal...
When inspecting you can see the line height is not right

![image](https://github.com/piitaya/lovelace-mushroom/assets/42821995/c80da2da-fe16-41ce-a518-742f162b3e61)

In the inspect code I see these are set regardless of font size
```
--card-primary-line-height: var(--mush-card-primary-line-height, 20px);
--card-secondary-line-height: var(--mush-card-secondary-line-height, 16px);
```

with `--card-primary-line-height: 1;`

![image](https://github.com/piitaya/lovelace-mushroom/assets/42821995/9f690ef1-b647-4e5b-91bf-7aec21a1e4ee)

**Comment by Je-sse** [comment] 2024-02-04 15:05
I can confirm that adding these two lines solves the issue:

```
       --card-primary-line-height: 1;
       --card-secondary-line-height: 1;
```

This is the entire code:

```
type: custom:mushroom-template-card
primary: '{{ now().strftime(''%H:%M'') }}'
icon: mdi:timelapse
secondary: '{{ now().strftime(''%d %B'') }}'
card_mod:
  style: |
    ha-card {
       --card-primary-font-size: 60px;
       --card-secondary-font-size: 30px;
       --card-primary-line-height: 1;
       --card-secondary-line-height: 1;
    }
    :host {
       --mush-icon-symbol-size: 1.75em;
       --mush-icon-size: 2.75em;
    }
```

I can also confirm that the issue still persists in version 3.4.1

**Comment by piitaya** [comment] 2024-02-06 17:09
Hi 👋 Some theme variables have been changed to use the default font style of tile card (https://github.com/piitaya/lovelace-mushroom/pull/1348/files#diff-47d2527b2c38615d2cd4f5c1c06a18c0bdb9b66519e468bba99344b5d9cadd6fR19-R26)
Mushroom support with card mod is not guarantee because it's not officially supported but you can find help in the [community forum](https://community.home-assistant.io/t/mushroom-cards-build-a-beautiful-dashboard-easily/388590)

I close this issue as card mod support is not provided in this repo.

**Closed by piitaya** 2024-02-06 17:09 UTC
Labels: bug

**Comment by sdholden28** [comment] 2024-02-06 19:20
> I can confirm that adding these two lines solves the issue:
> 
> ```
>        --card-primary-line-height: 1;
>        --card-secondary-line-height: 1;
> ```
> 
> This is the entire code:
> 
> ```
> type: custom:mushroom-template-card
> primary: '{{ now().strftime(''%H:%M'') }}'
> icon: mdi:timelapse
> secondary: '{{ now().strftime(''%d %B'') }}'
> card_mod:
>   style: |
>     ha-card {
>        --card-primary-font-size: 60px;
>        --card-secondary-font-size: 30px;
>        --card-primary-line-height: 1;
>        --card-secondary-line-height: 1;
>     }
>     :host {
>        --mush-icon-symbol-size: 1.75em;
>        --mush-icon-size: 2.75em;
>     }
> ```
> 
> I can also confirm that the issue still persists in version 3.4.1

Prior to v3.4.0, the value for line-height was 1.5. So if you're just trying to "undo the changes" you can add the below to your theme or card-mod-theme or however you're doing it, and you won't have to change 1000 lovelace cards.
--card-primary-line-height 1.5;
--secondary-line-height: 1.5;
