### ISSUE TITLE
Room card

### ISSUE THREAD

**Issue by tivoo** [piitaya/lovelace-mushroom#304] opened 2022-04-14 08:54 UTC
Room card from Minimalist UI as MushRoom card:
https://ui-lovelace-minimalist.github.io/UI/usage/cards/card_room/

**Comment by piitaya** [comment] 2022-04-14 09:29
Duplicate of #55.
It's not necessary to open issues AND discussions 😅

**Closed by piitaya** 2022-04-14 09:29 UTC
Labels: enhancement
