### ISSUE TITLE
[Bug]: Mushroom Card not Showing Up on Web Browser

### ISSUE THREAD

**Issue by retracdev** [piitaya/lovelace-mushroom#1582] opened 2024-11-10 19:37 UTC
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [x] I did a search to see if there is a similar issue or if a pull request is open.
- [x] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

It says that there is no type of card called "mushroom-entity-card" but there is.

### Expected Behavior

To show the card.

### Steps To Reproduce

Idk I was on iOS 12 for a dashboard and the error pops up

### Context

???

### Environment

```markdown
- Browser: Safari/HA App - tried both, they both dont work
- HA Version: ?
- Mushroom: 4.10
```

**Comment by formatBCE** [comment] 2024-11-11 04:09
After update to 4.10 some browsers stopped showing Mushroom chip cards (custom component doesn't exist). Reverted back to 4.0.8, it works again.

**Comment by formatBCE** [comment] 2024-11-11 06:26
> > After update to 4.10 some browsers stopped showing Mushroom chip cards (custom component doesn't exist). Reverted back to 4.0.8, it works again. I believe new libraries versions aren't compatible with older browsers (i personally have trouble with Lenovo Clock 2, which has pretty old Android system webview with no options to upgrade. Bummer if i'll have to ditch Mushroom because of this...
> 
> I also have a Lenovo Clock 2 with the same problem. I am thinking to root it using [this ](https://github.com/ThomasPrior/LenovoSmartClock2) method. It seems you can update the webview. The installed version is 74.0.3729.186. The link has a way to install a new version after rooting. I tried just sideloading but it won't install. 

Yes, need to root. I tried to avoid that, but looks like it's giving more and more troubles... Will have to root.

**Comment by mtgpcs** [comment] 2024-11-11 06:29
@formatBCE Same. I don't want to but it caused some problems with other cards but I was holding off until I had to. I have a spare one in the box not sure if I should do that one first or this one.

**Comment by IzzIsHOr** [comment] 2024-11-11 16:40
On my older iPad AIR1 4.10 shows CUSTOM ELEMENT DOESN'T EXIST, probably due to lit library I guess?

4.0.8 works great, 4.10 does not.

https://github.com/user-attachments/assets/91d37e19-8c23-4612-a25b-f39190adf77a
https://github.com/user-attachments/assets/e3fed4d9-9e04-447e-b660-93bdc56bbecc

**Comment by piitaya** [comment] 2024-11-11 16:50
Can you share the logs from the browser console?

**Comment by formatBCE** [comment] 2024-11-11 16:52
> Can you share the logs from the browser console? 

For Lenovo Clock 2 it's impossible unfortunately.... :(

**Comment by bdattilo** [comment] 2024-11-11 17:52
I believe this is the same issue as https://github.com/piitaya/lovelace-mushroom/issues/1202 which was subsequently fixed.

**Comment by retracdev** [comment] 2024-11-12 23:15
It is something with version 4.10 that interferes with something with cookies or logs on devices. Removing the integration, then heading to HACS and installing version **4.08** fixes it for me.

**Comment by retracdev** [comment] 2024-11-12 23:20
I also noticed no matter _what_ browser I used, Safari, etc. and even the HA companion app, it said that the “custom element doesn’t exist” till downgrading.

**Comment by PKort** [comment] 2024-11-13 13:30
I tested on Lenovo Tab M10 running Android 10 - issue is still present in 4.1.1. 
Rolling back to v4.0.8 again.

**Comment by mckochan** [comment] 2024-11-13 15:17
Thank you for the quick fix!
Tested working on Wink Relay (Android 4.3)!

**Comment by piitaya** [comment] 2024-11-13 17:39
> Does it also imply that it now should work with casting a dashboard to a google nest hub?

I didn't tested as I don't have a cast device available but it should. Can you test?

**Comment by formatBCE** [comment] 2024-11-13 18:12
Confirmed fix on Lenovo Clock 2, no root. Thank you so much!

**Comment by piitaya** [comment] 2024-11-13 20:38
Thank you all for the feedbacks. I close the issue.

**Closed** 2024-11-13 20:38 UTC
Labels: bug

**Comment by retracdev** [comment] 2024-11-14 00:51
# Thank you so much! The bug has been fixed.

**Comment by ericcastro** [comment] 2024-12-09 11:54
just chiming in, this is fixed in iOS 12.5.7 both on iPad mini 2 and iPhone 5S

a lot of custom cards are having this problem since recent HA releases, so I will try to point them here so they know how to fix it... as I don't expect HA to fix it themselves

thanks a lot !

**Comment by thoompje** [comment] 2025-01-05 20:01
> just chiming in, this is fixed in iOS 12.5.7 both on iPad mini 2 and iPhone 5S
> 
> 
> 
> a lot of custom cards are having this problem since recent HA releases, so I will try to point them here so they know how to fix it... as I don't expect HA to fix it themselves
> 
> 
> 
> thanks a lot !

Having exactly the same with a lot of custom elements. Suddenly nothing is working anymore on my ios app. Any fix already for this?

**Comment by carlicopter117** [comment] 2025-01-07 06:42
same here. got exactly the same issue with mushroom 4.2.1 and HA 2025.1

**Comment by mtgpcs** [comment] 2025-01-07 08:15
> > just chiming in, this is fixed in iOS 12.5.7 both on iPad mini 2 and iPhone 5S
> > a lot of custom cards are having this problem since recent HA releases, so I will try to point them here so they know how to fix it... as I don't expect HA to fix it themselves
> > thanks a lot !
> 
> Having exactly the same with a lot of custom elements. Suddenly nothing is working anymore on my ios app. Any fix already for this?

Go to Home Assistant settings and verify your HACS is not in "failed to setup". I had to hit configure, then submit then reload. Then HACS loaded and there was an update to HACS. I have two HA instances and this happened on both. It wasn't mushroom card related.

**Comment by carlicopter117** [comment] 2025-01-07 08:24
i did it and checked everything. everything is running and uptodate. i downgraded Mushroom from v4.2.1 to 4.1.0 and everything is running and looking well

**Comment by bdattilo** [comment] 2025-02-28 22:18
This appears to be broken again in 4.3.0.

**Comment by piitaya** [comment] 2025-03-01 08:24
Please follow the steps here : https://github.com/piitaya/lovelace-mushroom?tab=readme-ov-file#troubleshooting

If it doesn't work, please reopen an issue as it might not be related to this old closed issue.
