### ISSUE TITLE
[Bug]: Script entity in Entity Card

### ISSUE THREAD

**Issue by alexreddy78** [piitaya/lovelace-mushroom#845] opened 2022-11-10 18:49 UTC
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue.

### Current Behavior

After update to latest Mushroom 2.3.5, entity card for scripts is always shows color icon (as for ON state).

### Expected Behavior

OFF state for scripts must have grey/inactive state in Entity card

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: Edge
- HA Version: latest
- Mushroom: latest
```

**Comment by piitaya** [comment] 2022-11-10 19:06
Hello! It's a duplicate of https://github.com/piitaya/lovelace-mushroom/issues/840. It will be fixed.

**Closed** 2022-11-10 19:06 UTC
Labels: bug
