### ISSUE TITLE
[Feature]: Change / Customize cover status description

### ISSUE THREAD

**Issue by srodighiero** [piitaya/lovelace-mushroom#564] opened 2022-06-19 08:13 UTC
### Is your feature request related to a problem?

Currently the percentage position is reported as "unknown".
![image](https://user-images.githubusercontent.com/4833164/174471897-0e1f5378-f56f-41fd-b719-2d3f8e5e97c2.png)

### Describe the solution you'd like

Would be more "elegant" to remove it, or at least have the possbility to customize it or leave just the % status

**Comment by srodighiero** [comment] 2022-06-20 14:02
Yes, but I wanted to use the controls/buttons

**Comment by srodighiero** [comment] 2022-06-20 14:54
It's the localtuya integration. I agree with you that probably this should be "fixed" by the integration

**Comment by KTibow** [comment] 2022-07-01 18:37
Could you send a screenshot from Developer Tools of the entity's current state and attributes?

**Comment by piitaya** [comment] 2022-07-01 18:43
I think the integration doesn't set the state to open or closed 😟
But the fix must be in the integration side. Custom cards must not fix integration issues.

**Comment by KTibow** [comment] 2022-07-01 18:57
LocalTuya is more of a middleman, transforming the DPs (data points, basically number key to value pairs) of Tuya devices into HA entities. For example, here's one of my lights:
![image](https://user-images.githubusercontent.com/10727862/176953917-a252caf0-3b26-49c9-bbbd-c1d80666c385.png)
But I think this issue should be closed, as it's not related to Mushroom; if it was, it would be a duplicate of #144.

**Comment by piitaya** [comment] 2023-12-04 10:29
Tile card has `state_content` option and most of mushroom features. You can use it to solve your issue : https://www.home-assistant.io/dashboards/tile

**Closed by piitaya** 2023-12-04 10:29 UTC
Labels: enhancement
