### ISSUE TITLE
Gauge / Graph Card

### ISSUE THREAD

**Issue by Kev1000000** [piitaya/lovelace-mushroom#172] opened 2022-02-28 17:57 UTC
**Is your feature request related to a problem? Please describe.**
No problem!  I am just really interested in a sexy gauge or graph card for use on my dashboard.

**Describe the solution you'd like**
I use a lot of gauges and graphs on my dashboard, but the default Lovelace gauge is pretty ugly looking in comparison to the overall Mushroom aesthetic.  Having some sort of Mushroom gauge and graph card would go a long way to making Mushroom dashboards present quick info at glance while looking sexy.

**Describe alternatives you've considered**
I've tried using some other graph and gauge cards in HACS, but none of them feel quite close to the Mushroom design.

**Comment by bemble** [comment] 2022-02-28 20:07
Duplicate of #74

**Closed by bemble** 2022-02-28 20:07 UTC
Labels: enhancement
