### ISSUE TITLE
[Bug]: primary-text-color no longer working?

### ISSUE THREAD

**Issue by walk0080** [piitaya/lovelace-mushroom#1355] opened 2024-02-01 18:40 UTC
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

*** UPDATE: Tried reverting back to previous version using HACS with no luck... but after several attempts going back to 3.3.0, this is working again. Seems a bug introduced with latest 3.4.0 version? ***

As of today, the text just stays white and does not change based on state.

Not sure if this is specifically an issue with card-mod, or mushroom-template (both are using latest versions installed via HACS).

Screen cap from phone before HA refreshed:
![IMG_1727](https://github.com/piitaya/lovelace-mushroom/assets/22773927/59b443db-8d8c-4c6f-a6a2-331e688dd09c)

Screen cap from tablet showing colours missing:
![IMG_1794](https://github.com/piitaya/lovelace-mushroom/assets/22773927/44325e5c-c920-4823-9ba3-c84fcbc504f5)

### Expected Behavior

Certain text should be colour coded green (for yes) and red (for no).

This was working yesterday. Seems to be an issue on iOS/iPadOS Companion App, mobile and desktop browsers.

### Steps To Reproduce

Loaded up HA in Companion App this morning and text colours no longer change.

My phone was showing correct colours until I forced a Lovelace reload and then colours were gone.

Same issue on both HA Companion app on iPadOS/iOS, mobile Safari and desktop Chrome.

### Context

YAML state

```yaml
          - type: custom:mushroom-template-card
            primary: |-
              {% set state=states('input_boolean.dog_henry_feeding_required') %}
              {% if state=='on' %}
                Yes
              {% else %}
                No
              {% endif %}
            secondary: Feed Reqd?
            icon: ''
            entity: input_boolean.dog_henry_feeding_required
            icon_color: white
            tap_action:
              action: more-info
            hold_action:
              action: more-info
            double_tap_action:
              action: more-info
            multiline_secondary: false
            fill_container: false
            card_mod:
              style:
                mushroom-state-info $: |
                  .container {
                    --card-secondary-font-size: 14px;
                    --card-primary-font-size: 16px;
                  }
                .: |
                  ha-card {
                    {% set state=states('input_boolean.dog_henry_feeding_required') %}
                    {% if state=='on' %}
                      --primary-text-color: red
                    {% else %}
                      --primary-text-color: green
                    {% endif %}
                    }
```

### Environment

```markdown
- Browser: Safari (iPadOS 17.3, iOS 17.3)
- HA Version: Core 2024.1.6 | Frontend 20240104.0
- Mushroom: 3.4.0
- Card-Mod: 3.4.2
```

### Anything else?

I posted on the code-mod Github as well: [lovelace-card-mod Gifthub Issue 356](https://github.com/thomasloven/lovelace-card-mod/issues/356)

**Comment by djjoakim** [comment] 2024-02-01 19:06
I can confirm this problem, it happend with the latest mushroom update - i reversed back to 3.3.0 and it's working again.

**Comment by walk0080** [comment] 2024-02-01 19:10
Does in fact work with a standard HA card.

Went back to the previous version and was not resolved -- Will try 3.3.0 instead.

```yaml
type: entity
entity: input_boolean.dog_henry_feeding_required
card_mod:
  style: |
    ha-card {
      {% set state=states('input_boolean.dog_henry_feeding_required') %}
      {% if state=='on' %}
        --primary-text-color: red
      {% else %}
        --primary-text-color: green
      {% endif %}
      }
```

![IMG_1796](https://github.com/thomasloven/lovelace-card-mod/assets/22773927/a85d26a6-7c78-452a-a74c-5c1ae57ad10a)

**Comment by walk0080** [comment] 2024-02-01 19:14
> I can confirm this problem, it happend with the latest mushroom update - i reversed back to 3.3.0 and it's working again.

Tried going back to 3.3.0 mushroom and it does in fact work again. Not sure why previous attempts to revert back to 3.3.0 in HACS did not work even after clearing cache in HA Companion App. Thank you.

**Comment by sdholden28** [comment] 2024-02-01 19:28
There are definitlely issues related to card_mod. I had to revert back to 3.3 as well. I have a number of cards with larger font size set via card_mod. Prior to 3.4, the cards scale in size to match the font size. On 3.4, the cards revert to normal size and the text with the larger font size gets clipped.

**Comment by robertboccia** [comment] 2024-02-02 02:55
Same problem with text colour using card mod, wonder when this will be fixed?

**Comment by margatemarcel** [comment] 2024-02-03 08:18
I have the same problem and have reverted to v3.3.0 for now.

**Comment by julianfs** [comment] 2024-02-05 20:23
I also have the same issue, resolved by rolling back to v3.3.0.

**Comment by piitaya** [comment] 2024-02-06 17:10
Hi 👋 Some theme variables have been changed to use the default font style of tile card (https://github.com/piitaya/lovelace-mushroom/pull/1348/files#diff-47d2527b2c38615d2cd4f5c1c06a18c0bdb9b66519e468bba99344b5d9cadd6fR19-R26)
Mushroom support with card mod is not guarantee because it's not officially supported but you can find help in the [community forum](https://community.home-assistant.io/t/mushroom-cards-build-a-beautiful-dashboard-easily/388590)

I close this issue as card mod support is not provided in this repo.

**Closed** 2024-02-06 17:11 UTC
Labels: bug

**Comment by walk0080** [comment] 2024-02-06 17:55
That's unfortunate. Is there a workaround that you are aware of?

**Comment by rindlerblabla** [comment] 2024-02-06 17:57
> That's unfortunate. Is there a workaround that you are aware of?

Did you follow the link above? Here's the solution. https://github.com/piitaya/lovelace-mushroom/pull/1348#issuecomment-1923483825

**Comment by piitaya** [comment] 2024-02-06 18:00
When you have card mod issues, don't hesitate to look at the forum https://community.home-assistant.io/t/mushroom-cards-build-a-beautiful-dashboard-easily/388590 😊

**Comment by walk0080** [comment] 2024-02-06 18:42
Thank you - it does indeed work correctly with latest mushroom card version using `--card-primary-color` per https://github.com/piitaya/lovelace-mushroom/pull/1348#issuecomment-1923483825


```
            card_mod:
              style:
                mushroom-state-info $: |
                  .container {
                    --card-secondary-font-size: 14px;
                    --card-primary-font-size: 16px;
                  }
                .: |
                  ha-card {
                    {% set state=states('input_boolean.dog_henry_feeding_required') %}
                    {% if state=='on' %}
                      --card-primary-color: red
                    {% else %}
                      --card-primary-color: green
                    {% endif %}
                    }
```
