### ISSUE TITLE
[Bug]: Missing translation

### ISSUE THREAD

**Issue by dolenec** [piitaya/lovelace-mushroom#1138] opened 2023-05-08 14:38 UTC
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

The problem is that 1 specific string is not translated. In case that LED light is OFF then there in neverless of choosen GUI language there is text "off", but this text should be translatable.

and so on..

Picture of missing translation (marked with red color):
![image](https://user-images.githubusercontent.com/16633222/236852442-d31aaaf5-211c-49e6-8f07-164992d0d8b6.png)

### Expected Behavior

In **English** language should be:
Off
**German**:
Aus
**Italian**:
Spento
**Slovenian**:
Izklopljeno

and so on..

### Steps To Reproduce

Simply use my code in lovelace UI, and use own light entity.

### Context

YAML state
```
entities:
  - type: custom:mushroom-light-card
    entity: light.shelly_rgbw2_kuhinja1
    icon_color: grey
    show_brightness_control: true
    use_light_color: false
    show_color_control: false
    show_color_temp_control: false
    double_tap_action:
      action: more-info
    hold_action:
      action: more-info
    layout: horizontal
    fill_container: false
show_header_toggle: false
type: entities

```

### Environment

```markdown
- Browser: All (Firefox, Chrome, Phone browser)
- HA Version: 2023.5.2
- Mushroom: (up-to-date)
```

**Comment by brebtatv** [comment] 2023-05-11 21:54
I confirm also in the Czech language, it behaves randomly, sometimes it is translated, sometimes not. Translations in HA entities are always translated.

**Comment by brebtatv** [comment] 2023-05-11 21:55
The problem seems across the mushroom

**Comment by piitaya** [comment] 2023-06-06 11:59
The issue has been fixed with https://github.com/piitaya/lovelace-mushroom/pull/1074 and shipped in (https://github.com/piitaya/lovelace-mushroom/releases/tag/v2.6.2)[v2.6.2).

This issue is a duplicate of https://github.com/piitaya/lovelace-mushroom/issues/1114. Make sure to uninstall/reinstall, clear the cache, to fix the issue.

Also, if you use the mushroom-better-sliders fork, it's normal that you have the issue because the fix was done during April and the fork hasn't been updated since March.

**Closed by piitaya** 2023-06-06 11:59 UTC
Labels: bug
