### ISSUE TITLE
[Bug]: The version for this plugin can not be used with HACS.

### ISSUE THREAD

**Issue by yn36** [piitaya/lovelace-mushroom#1605] opened 2024-12-12 02:45 UTC
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

The version for this plugin can not be used with HACS.

<img width="1461" alt="image" src="https://github.com/user-attachments/assets/ea23ffc4-877c-43dc-a7eb-681c72e08735" />

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser:
- HA Version: Core:2024.12.2 Supervisor: 2024.11.4
- Mushroom: 
- HACS Version: 2.0.1
```

**Comment by piitaya** [comment] 2024-12-15 10:42
Do you have other informations to share ? I can not reproduce it.

**Comment by dusivk** [comment] 2024-12-18 16:15
This happens when an internet connection is not available, because HA can only run on the local network.
Ďusi

**Comment by piitaya** [comment] 2024-12-18 22:24
Ok so it's related to network issue. It's normal to not being able to install plugin if this no connection. May be the wording should be improved in hacs.
I close it as it's not a Mushroom issue.

**Closed by piitaya** 2024-12-18 22:24 UTC
Labels: bug
